# Generated by Django 3.0.1 on 2020-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execmember',
            name='sort_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
