# Generated by Django 3.0.1 on 2020-02-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datetime_created',
            field=models.DateField(),
        ),
    ]
