# Generated by Django 3.0.1 on 2020-02-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200204_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='datetime_created',
            new_name='date',
        ),
    ]
