# Generated by Django 3.0.1 on 2020-02-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200204_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='datetime_created',
            field=models.DateField(),
        ),
    ]
