# Generated by Django 3.0.1 on 2020-02-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200204_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='datetime_created',
            new_name='date',
        ),
    ]
