# Generated by Django 3.0.2 on 2020-02-05 03:27

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20200204_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='_text_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='_description_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='execmember',
            name='_description_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='execmember',
            name='description_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='_description_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
        migrations.AlterField(
            model_name='execmember',
            name='description',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
    ]
