# Generated by Django 3.0.1 on 2020-02-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20200204_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Event')),
            ],
        ),
    ]
