# Generated by Django 3.0.2 on 2020-02-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20200205_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('markdown', 'markdown')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('markdown', 'markdown')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='execmember',
            name='description_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('markdown', 'markdown')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('markdown', 'markdown')], default=None, max_length=30, null=True),
        ),
    ]
