# Generated by Django 3.0.1 on 2020-02-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_eventphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
