# Generated by Django 3.0.1 on 2020-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='sort_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
