# Generated by Django 3.0.1 on 2020-02-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_photo_sort_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, default='12:00:00'),
            preserve_default=False,
        ),
    ]
