# Generated by Django 3.0.1 on 2020-02-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='execmember',
            name='year_term_started',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
