# Generated by Django 3.0.1 on 2020-02-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_execmember_year_term_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
