# Generated by Django 3.0.1 on 2020-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20200205_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='past',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
