# Generated by Django 3.0.1 on 2020-02-07 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_project_past'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('associated_blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.BlogPost')),
            ],
        ),
    ]
