# Generated by Django 3.0.1 on 2020-02-07 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_blogpostimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('associated_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Project')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('associated_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Event')),
            ],
        ),
    ]
