# Generated by Django 3.0.1 on 2020-02-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_auto_20200207_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
