# Generated by Django 3.0.1 on 2020-02-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
