# Generated by Django 3.0.1 on 2020-02-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_event_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='past',
        ),
    ]
