# Generated by Django 3.0.1 on 2020-02-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_remove_project_past'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='preference',
            field=models.IntegerField(default=0),
        ),
    ]
