# Generated by Django 3.0.1 on 2020-02-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_eventimage_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
