# Generated by Django 3.0.1 on 2020-02-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_remove_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostimage',
            name='preference',
            field=models.IntegerField(default=0),
        ),
    ]
