# Generated by Django 3.0.1 on 2020-02-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_blogpostimage_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostimage',
            name='caption',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='eventimage',
            name='caption',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='caption',
            field=models.TextField(default=''),
        ),
    ]
