# Generated by Django 3.0.1 on 2020-02-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_auto_20200209_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostimage',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
    ]
