# Generated by Django 3.0.1 on 2020-02-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_auto_20200210_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='preference',
        ),
    ]
