# Generated by Django 3.0.1 on 2020-02-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_remove_blogpostimage_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
