# Generated by Django 3.0.1 on 2020-02-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_auto_20200210_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
