# Generated by Django 3.0.1 on 2020-02-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0038_auto_20200215_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='date_added',
        ),
    ]
