# Generated by Django 3.0.1 on 2020-02-15 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0039_remove_subscriber_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
